### PR TITLE
Add changelog for v0.38

### PR DESCRIPTION
**Pull request by penguineer**
Fix for #102

### CODE REVIEW

**Comment by penguineer** [comment]
"Close" ist nicht "Merge" …

**Comment by LeSpocky** [comment]
Okay that was maybe merged a little too fast, what about mentioning the following changes in the changelog?

* ea7dbd8d0c6e8920031b814b224c711dc54c2789
* 1b2ef311f08caeb341bd20360d46b72fb157cf93
* 43c85f7f2e649e072f567bcfc5dc72b81a1566f1

**Comment by penguineer** [comment]
Maybe we need a specification of what goes into the changelog.

https://github.com/FreifunkMD/site-ffmd/commit/ea7dbd8d0c6e8920031b814b224c711dc54c2789 is only relevant for development (i.e. building the FW yourself)

https://github.com/FreifunkMD/site-ffmd/commit/1b2ef311f08caeb341bd20360d46b72fb157cf93
https://github.com/FreifunkMD/site-ffmd/commit/43c85f7f2e649e072f567bcfc5dc72b81a1566f1
are for rollout

Who is the target audience for the changelog?

On the other hand: If we specify the target gluon version, why link all the intermediate changelogs?

**Comment by LeSpocky** [comment]
This repository is only needed for building the firmware, so audience is people interested in the firmware in general and people interested in building it. In the past we added at least changes to the build script to the changelog, and in v0.28 also changes to the keys.

We link all the intermediate gluon changelogs, because there is no single gluon changelog with all the changes up to a certain version. Those add up and you have to read all of them to see what changed without missing something.

**Comment by penguineer** [comment]
Then where is the changelog for the users?

**Comment by LeSpocky** [comment]
> Then where is the changelog for the users?

I would say, there is none, at least not in a way which is tracked by some version control. There were however blogposts covering the important changes. See for the last four releases:

* https://md.freifunk.net/2016/02/firmware-0-34-freigegeben/
* https://md.freifunk.net/2016/03/firmware-0-35-freigegeben/
* https://md.freifunk.net/2016/05/firmware-0-36-freigegeben/
* https://md.freifunk.net/2016/07/firmware-0-37-freigegeben/

Probably those were a handcrafted summary and a mix of our changes with the gluon stuff?

**Pull request merged**
