### PR TITLE
WIP: Gluon update & configuration changes (especially regarding the build process)

### PR DESCRIPTION
**Pull request by GoliathLabs**
Good day,
I've updated the configuration to be more readable. The Site.{conf,mk} has been updated to include newer targets, packages, and some configuration changes. Gluon has been updated to the latest version, which is already used by my "home community" freifunk munich. The new ath79 target has been introduced for supported devices. I could add some patches later as the DIR615C1 has very little flash which may not be enough for the current firmware to properly fit on it.

I would be very happy to receive feedback.
I hope that with this I can contribute something to the ffmd community! 😄

### CODE REVIEW

**Comment by GoliathLabs** [comment]
Added the DLINK patch

**Comment by penguineer** [comment]
Thank you very much for your contribution!

We are not following the batman gluon branch anymore because we are trying to switch to babel (2nd network already running) and kept the 2016 gluon for batman to avoid switching the wireless protocol.

Other than that I am happy to integrate contributions.

**Comment by GoliathLabs** [comment]
Do you mean the mesh protocol? (ibss)

**Comment by penguineer** [comment]
> Do you mean the mesh protocol? (ibss)

Yesss.

Since we want to make the switch to Babel anyways, we decided to change the mesh protocol only once.

**Pull request closed without merging**
